esphome:
  name: garage-led-monitor
  friendly_name: "Garage Visual Indicator"
  
  # Vital settings for ESP32-C3 SuperMini to enable USB logging
  platformio_options:
    build_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=1"
      - "-DARDUINO_USB_MODE=1"

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino

# Force logs to USB Serial/JTAG instead of UART
logger:
  hardware_uart: USB_SERIAL_JTAG
  level: DEBUG

# Connection settings optimized for weak signal / PCB antenna
wifi:
  ssid: "YOUR_WIFI_SSID"      # <-- CHANGE THIS
  password: "YOUR_WIFI_PASSWORD" # <-- CHANGE THIS
  
  # Crucial for stable connection on SuperMini boards
  power_save_mode: none 
  output_power: 20dB

api:
  encryption:
    key: "YOUR_API_ENCRYPTION_KEY" # <-- Generate a new key in ESPHome dashboard

# --- LOGIC ---

binary_sensor:
  # 1. Door Status (Source: Zigbee sensor in Home Assistant)
  - platform: homeassistant
    name: "Garage Door Input"
    entity_id: binary_sensor.your_zigbee_door_contact # <-- CHANGE TO REAL HA ENTITY ID
    id: ha_door_status
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: ha_door_status
            then:
              # Door OPEN: Standard warning strobe
              - light.turn_on:
                  id: onboard_led
                  effect: "Strobe Warning"
            else:
              # Door CLOSED: Turn off LED
              - light.turn_off: onboard_led

  # 2. Close Button Listener (Source: Switch/Button in Home Assistant)
  - platform: homeassistant
    name: "Garage Close Button Trigger"
    entity_id: switch.your_garage_close_switch # <-- CHANGE TO REAL HA ENTITY ID
    id: ha_close_button
    on_press:
      then:
        # Only activate if door is currently open
        - if:
            condition:
              binary_sensor.is_on: ha_door_status
            then:
              # Feedback: Fast aggressive strobe to indicate "Closing command received"
              - light.turn_on:
                  id: onboard_led
                  effect: "Fast Closing Strobe"
              
              # Wait 30s for the door to travel
              - delay: 30s
              
              # Fallback: If door is still open after 30s, revert to standard warning
              - if:
                  condition: 
                    binary_sensor.is_on: ha_door_status
                  then:
                    - light.turn_on:
                        id: onboard_led
                        effect: "Strobe Warning"

light:
  - platform: monochromatic
    name: "Onboard LED"
    id: onboard_led
    output: led_gpio
    effects:
      # Effect 1: Standard Warning (0.5s ON / 0.5s OFF)
      - strobe:
          name: "Strobe Warning"
          colors:
            - state: true
              brightness: 100%
              duration: 500ms
            - state: false
              duration: 500ms
      
      # Effect 2: Closing Action (0.1s ON / 0.1s OFF)
      - strobe:
          name: "Fast Closing Strobe"
          colors:
            - state: true
              brightness: 100%
              duration: 100ms
            - state: false
              duration: 100ms

output:
  - platform: ledc
    pin:
      number: GPIO8      # Standard LED pin for ESP32-C3 SuperMini
      inverted: true     # Active LOW (set to false if LED logic is reversed)
    id: led_gpio
